repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
        args: ["--fix"]
        exclude: migrations/versions/*
      - id: ruff-format
        args: ["--check"]
        additional_dependencies: [black==24.4.2]
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        args: ["--diff", "--check"]
