app = "crunevo-admin"
# Se recomienda usar la misma región que la aplicación principal para reducir latencia.
primary_region = "gru"

[build]
  dockerfile = "Dockerfile"

[deploy]
  release_command = "flask db upgrade"

[env]
  FLASK_APP = "crunevo.wsgi_admin:application"
  FLASK_ENV = "production"
  ADMIN_INSTANCE = "1"
  MAINTENANCE_MODE = "0"
  PORT = "8080"
  SESSION_COOKIE_HTTPONLY = "true"

[experimental]
  auto_rollback = true

# Se moderniza la configuración de servicios a [http_service] para consistencia
# y para aprovechar las nuevas funcionalidades de Fly.io.
[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0 # Se puede poner a 0 si el panel no necesita estar siempre activo

  [[http_service.checks]]
    interval = '10s'
    timeout = '2s'
    grace_period = '5s'
    method = 'GET'
    path = "/healthz"

[[vm]]
  memory_mb = 1024 # Usar memory_mb para consistencia
  cpu_kind = "shared"
  cpus = 1
