app = "crunevo-admin"
primary_region = "gru"

[build]
  dockerfile = "Dockerfile"

[deploy]
  release_command = "flask db upgrade"

[env]
  FLASK_APP = "crunevo.wsgi_admin:app"
  FLASK_ENV = "production"
  ADMIN_INSTANCE = "1"
  MAINTENANCE_MODE = "0"
  PORT = "8080"
  SESSION_COOKIE_HTTPONLY = "true"

[experimental]
  auto_rollback = true

[[services]]
  protocol = "tcp"
  internal_port = 8080

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.http_checks]]
    interval     = "10s"
    timeout      = "2s"
    grace_period = "5s"
    method       = "get"
    path         = "/healthz"
    protocol     = "http"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
