# fly.toml app configuration file for crunevo2

app = 'crunevo2'
primary_region = 'bog'

[build]
  dockerfile = 'Dockerfile'

[deploy]
  release_command = "flask db upgrade"

[env]
  FLASK_APP = 'crunevo.wsgi'
  FLASK_ENV = 'production'
  PORT = "8080"

[experimental]
  auto_rollback = true

[[services]]
  protocol = 'tcp'
  internal_port = 8080

  [[services.ports]]
    port = 80
    handlers = ['http']

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [[services.tcp_checks]]
    interval = '10s'
    timeout = '2s'

  [[services.http_checks]]
    interval     = '10s'
    timeout      = '2s'
    grace_period = '5s'
    method       = 'get'
    path         = '/healthz'
    protocol     = 'http'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

# If using shared IPv4, point the root domain (crunevo.com)
# to 66.241.125.104 with an A record.
