# fly.toml app configuration file for crunevo2

app = 'crunevo2'
primary_region = 'bog'

[build]
  dockerfile = 'Dockerfile'

[deploy]
  release_command = 'flask db upgrade'


[env]
  FLASK_APP = 'crunevo.wsgi:app'
  FLASK_ENV = 'production'
  PORT = "8080"

[experimental]
  auto_rollback = true

[http_service]
  internal_port = 8080

  [[http_service.checks]]
    grace_period = '15s'
    interval = '10s'
    timeout = '5s'
    method = 'get'
    path = '/'
    protocol = 'http'

[[services]]
  protocol = 'tcp'
  internal_port = 8080

  [[services.ports]]
    port = 80
    handlers = ['http']

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [[services.tcp_checks]]
    interval = '10s'
    timeout = '2s'

  [[services.http_checks]]
    interval     = '10s'
    timeout      = '2s'
    grace_period = '5s'
    method       = 'get'
    path         = '/health'
    protocol     = 'http'

[[vm]]
  memory_mb = 2048
  cpu_kind = 'performance'
  cpus = 1

# If using shared IPv4, point the root domain (crunevo.com)
# to 66.241.125.104 with an A record.
