app = "crunevo2"

[build]
  dockerfile = "Dockerfile"

[env]
  PYTHONUNBUFFERED = "1"
  FLASK_APP = "crunevo.app"

[deploy]
  release_command = "flask db upgrade"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 8080
