app = "crunevo2"

[build]
  dockerfile = "Dockerfile"

[env]
  FLASK_APP = "crunevo.wsgi"

[deploy]
  release_command = "flask db upgrade"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.tcp_checks]]
    interval = "10s"
    timeout = "2s"
