app = "crunevo2"

[build]
  dockerfile = "Dockerfile"

[env]
  FLASK_APP = "crunevo.wsgi"

[deploy]
  release_command = "flask db upgrade"

[[services]]
  internal_port = 8080
  protocol = "tcp"
  [[services.ports]]
    handlers = ["http"]
    port = 8080
