"""add purchase and credits

Revision ID: 1a80ed700a38
Revises: e8fb5094eccf
Create Date: 2025-06-22 02:42:13.007380
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1a80ed700a38"
down_revision = "e8fb5094eccf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "achievement",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("icon", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "purchase",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=True),
        sa.Column("price_soles", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("price_credits", sa.Integer(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["product_id"], ["product.id"]),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("product", schema=None) as batch_op:
        batch_op.add_column(sa.Column("price_credits", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("is_featured", sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column("credits_only", sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column("is_popular", sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column("is_new", sa.Boolean(), nullable=True))

    with op.batch_alter_table("user_achievement", schema=None) as batch_op:
        # batch_op.add_column(sa.Column("timestamp", sa.DateTime(), nullable=True))  # Ya existe
        batch_op.drop_column("earned_at")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_achievement", schema=None) as batch_op:
        batch_op.add_column(sa.Column("earned_at", sa.DateTime(), nullable=True))
        # batch_op.drop_column("timestamp")  # No eliminar porque ya existía

    with op.batch_alter_table("product", schema=None) as batch_op:
        batch_op.drop_column("is_new")
        batch_op.drop_column("is_popular")
        batch_op.drop_column("credits_only")
        batch_op.drop_column("is_featured")
        batch_op.drop_column("price_credits")

    op.drop_table("purchase")
    op.drop_table("achievement")
    # ### end Alembic commands ###
