"""Add mostrar_tienda_perfil field to User model

Revision ID: add_mostrar_tienda_perfil
Revises: 
Create Date: 2025-08-06 18:03:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_mostrar_tienda_perfil'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mostrar_tienda_perfil', sa.Boolean(), nullable=True, default=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('mostrar_tienda_perfil')
    # ### end Alembic commands ###