"""post fields update

Revision ID: c0fc81e1405b
Revises: 63782dce56ec
Create Date: 2025-06-18 03:03:42.453853

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c0fc81e1405b"
down_revision = "63782dce56ec"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.add_column(sa.Column("author_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("file_url", sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column("likes", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("type", sa.String(length=20), nullable=True))
        batch_op.alter_column(
            "content",
            existing_type=sa.TEXT(),
            type_=sa.String(length=280),
            existing_nullable=False,
        )
        batch_op.drop_column("user_id")
        batch_op.create_foreign_key(
            "fk_post_author_id_user", "user", ["author_id"], ["id"]
        )
        batch_op.drop_column("image_url")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("image_url", sa.VARCHAR(length=255), nullable=True)
        )
        batch_op.add_column(sa.Column("user_id", sa.INTEGER(), nullable=True))
        batch_op.drop_constraint("fk_post_author_id_user", type_="foreignkey")
        batch_op.drop_column("author_id")
        batch_op.create_foreign_key("fk_post_user_id_user", "user", ["user_id"], ["id"])
        batch_op.alter_column(
            "content",
            existing_type=sa.String(length=280),
            type_=sa.TEXT(),
            existing_nullable=False,
        )
        batch_op.drop_column("type")
        batch_op.drop_column("likes")
        batch_op.drop_column("file_url")

    # ### end Alembic commands ###
