"""Backward compatibility module for feed routes."""

from crunevo.models import FeedItem  # re-export for tests
from .feed import feed_bp
from .feed.views import (
    feed_home,
    create_post,
    view_feed,
    trending,
    view_post,
    view_post_photo,
    user_posts,
    user_notes,
    editar_post,
    eliminar_post,
    report_post,
)
from .feed.api import (
    like_post,
    comment_post,
    api_comments,
    api_post_detail,
    toggle_save,
    donate_post,
    api_chat,
    api_analizar,
    api_feed,
    api_quickfeed,
    api_trending,
    search_posts,
    load_feed,
)

__all__ = [
    "feed_bp",
    "feed_home",
    "create_post",
    "view_feed",
    "trending",
    "view_post",
    "view_post_photo",
    "user_posts",
    "user_notes",
    "editar_post",
    "eliminar_post",
    "report_post",
    "like_post",
    "comment_post",
    "api_comments",
    "api_post_detail",
    "toggle_save",
    "donate_post",
    "api_chat",
    "api_analizar",
    "api_feed",
    "api_quickfeed",
    "api_trending",
    "search_posts",
    "load_feed",
    "FeedItem",
]
