class AchievementCodes:
    PRIMER_APUNTE = "primer_apunte"
    TOP_3 = "top_3"
    DONADOR = "donador"
    CONECTADO_7D = "conectado_7d"
    COMPARTIDOR = "compartidor"
    DESCARGA_100 = "100_descargas"
    LIKE_100 = "100_likes"
    CREDITOS_100 = "100_creditos"
    TUTOR_ACTIVO = "tutor_activo"
    EMBAJADOR_CRUNEVO = "embajador_crunevo"
    ALIADO_EDUCATIVO = "aliado_educativo"
