class CreditReasons:
    APUNTE_SUBIDO = "apunte_subido"
    DONACION = "donación"
    COMPRA = "compra"
    AGRADECIMIENTO = "agradecimiento"
    VOTO_POSITIVO = "voto_positivo"
    DONACION_FEED = "donación_feed"
    RACHA_LOGIN = "racha_login"
    ACTIVIDAD_SOCIAL = "actividad_social"
    REFERIDO = "referido"
    LOGRO = "logro"
