NOTE_CATEGORIES = [
    "Actividad Física",
    "Administración",
    "Álgebra",
    "Apuntes Libres",
    "Artes Visuales",
    "Aritmética",
    "Arte",
    "Biología",
    "Ciencia y Ambiente",
    "Ciencias Naturales",
    "Ciencias Sociales",
    "Comprensión Lectora",
    "Comunicación",
    "Constitución y Derechos Humanos",
    "Contabilidad",
    "Currículo",
    "Derecho",
    "Didáctica",
    "Economía",
    "Educación Bilingüe",
    "Educación Cívica",
    "Educación Digital",
    "Educación Física",
    "Educación para el Trabajo",
    "Emprendimiento",
    "Estadística",
    "Filosofía",
    "Formación Ciudadana",
    "Francés",
    "Física",
    "Geografía",
    "Geometría",
    "Gestión Educativa",
    "Historia",
    "Informática",
    "Inglés",
    "Lengua y Literatura",
    "Lenguas Originarias",
    "Marketing",
    "Matemática",
    "Metodología de la Investigación",
    "Misceláneos",
    "Música",
    "Nutrición",
    "Ortografía",
    "Otros",
    "Pedagogía",
    "Periodismo",
    "Programación",
    "Proyecto de Investigación",
    "Psicología",
    "Publicidad",
    "Química",
    "Razonamiento Matemático",
    "Religión y Valores",
    "Robótica",
    "Salud",
    "Sociología",
    "Teatro",
    "Tecnología",
    "Tesis",
    "Trigonometría",
]
