STORE_CATEGORIES = {
    "Material Académico": [
        "Libros físicos",
        "Libros en PDF",
        "Apuntes impresos",
        "Resúmenes y guías",
        "Cuadernos con contenido útil",
        "Plantillas y formatos editables",
        "Diccionarios y enciclopedias",
    ],
    "Servicios Educativos": [
        "Tutorías personalizadas",
        "Resolución de ejercicios",
        "Corrección de tareas o trabajos",
        "Diseño de PPT o infografías educativas",
        "Clases grabadas",
        "Sesiones de Zoom / Meet grabadas",
    ],
    "Material de oficina y estudio": [
        "Lápices, lapiceros y plumones",
        "Cuadernos, hojas y folders",
        "Estuches, reglas y tajadores",
        "Calculadoras",
        "Cartucheras y organizadores",
        "Material de dibujo técnico",
        "Papelotes, cartulinas y marcadores",
    ],
    "Electrónica y tecnología": [
        "Laptops",
        "Celulares",
        "Accesorios: cargadores, mouse, USBs",
        "Audífonos, parlantes",
        "Teclados y mousepads",
        "Software educativo o licencias",
    ],
    "Ropa y accesorios universitarios": [
        "Polos con logo de la universidad",
        "Buzos, casacas, gorras",
        "Pulseras, llaveros o pines personalizados",
        "Mochilas o bolsos de estudiante",
        "Gafas protectoras para laboratorio",
    ],
    "Productos hechos a mano / artesanales": [
        "Manualidades",
        "Decoraciones de escritorio",
        "Accesorios tejidos (bufandas, gorros)",
        "Libretas artesanales",
        "Souvenirs temáticos",
    ],
    "Comidas y snacks": [
        "Chocolates / chocotejas",
        "Galletas o pasteles caseros",
        "Jugos o postres",
        "Snacks empaquetados",
        "Productos para eventos (cumpleaños, campañas, etc.)",
    ],
    "Herramientas útiles": [
        "Herramientas básicas (destornilladores, alicates)",
        "Kits de física o electrónica",
        "Material de laboratorio",
        "Cinta, pegamento, tijeras, silicona",
        "Estantes, soportes o escritorios",
    ],
    "Cuidado personal y bienestar": [
        "Mascarillas",
        "Gel antibacterial",
        "Cremas, jabones artesanales",
        "Lentes con filtro azul",
        "Accesorios de relajación (antiestrés, etc.)",
    ],
    "Otras categorías (misc.)": [
        "Servicios de impresión",
        "Ropa en general (2da mano o nueva)",
        "Objetos coleccionables o decorativos",
        "Juegos de mesa o cartas",
        "Venta de artículos por mudanza",
    ],
}
